# Generated by Django 5.0 on 2024-05-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiclistening',
            name='listen_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
