# Generated by Django 5.0 on 2024-05-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_musiclistening_listen_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
