# Generated by Django 5.0 on 2024-05-05 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_music_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musiclistening',
            name='music',
        ),
        migrations.RemoveField(
            model_name='musiclistening',
            name='listener',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.DeleteModel(
            name='MusicListening',
        ),
    ]
