# Generated by Django 5.0 on 2024-05-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_music_favorite_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusicListening',
        ),
    ]
