# Generated by Django 5.0 on 2024-05-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_delete_musiclistening'),
        ('user', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='music.music'),
        ),
    ]
